#!/bin/sh

# Invoke all scripts that build reports.

# Switch to the directory this script is placed in.
cd `dirname $_`

./get-explosives.php
./get-buildcrashes.php
./get-flashhangs.php
./get-flashhangdetails.php
