#!/bin/sh

# Invoke all scripts that build reports.

php get-buildcrashes.php
php get-explosives.php
php get-flashhangs.php $@
php get-flashversions.php $@
#./get-components.php
php get-startupcrashes.php
#./get-devicecrashes.php
php get-topcrashes.php
php get-b2gcrashes.php
php get-socorrodata.php
php get-socorrobugsweekly.php
php get-crashbugsweekly.php
php get-qabugstats.php

# indicate the latest processed date
date -d "yesterday" +"%F" > latestdate.txt
